export {
  AMERICAN_FOOTBALL_BUTTON_DANGER as TENNIS_BUTTON_DANGER,
  AMERICAN_FOOTBALL_BUTTON_POSITIVE as TENNIS_BUTTON_POSITIVE,
  AMERICAN_FOOTBALL_BUTTON_PRIMARY as TENNIS_BUTTON_PRIMARY,
  AMERICAN_FOOTBALL_BUTTON_SECONDARY as TENNIS_BUTTON_SECONDARY,
  AMERICAN_FOOTBALL_FORM_MODES as TENNIS_FORM_MODES,
  AMERICAN_FOOTBALL_INPUT_CLASS as TENNIS_INPUT_CLASS,
  AMERICAN_FOOTBALL_LABEL_CLASS as TENNIS_LABEL_CLASS,
  AMERICAN_FOOTBALL_SELECT_CLASS as TENNIS_SELECT_CLASS,
  americanFootballModeTabClass as tennisModeTabClass,
  americanFootballSubmitButtonClass as tennisSubmitButtonClass,
  isCanonicalId,
  nullableString,
  parseOptionalInt,
  parseOptionalNumber,
  parseRequiredInt,
  requireCanonicalId,
  truncateCanonicalId,
  type AmericanFootballFormMode as TennisFormMode,
} from '../american-football-forms/shared';
